name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  gdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get requirements
        run: cp "$PWD/.github/dist/requirements.txt" .

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run gdlint
        run : gdlint .
        continue-on-error: true
