name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  gdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install 'gdtoolkit==3.*'

      - name: Run gdlint
        run : gdlint .
